// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFXcdygZRy5CjPYG6h1auskYoQruk0j0M',
    appId: '1:312149557905:web:65069593088370ffe2f530',
    messagingSenderId: '312149557905',
    projectId: 'flutterauth-fe0ce',
    authDomain: 'flutterauth-fe0ce.firebaseapp.com',
    storageBucket: 'flutterauth-fe0ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAT1uq3VM-ZwMT5EhYMkQot9YnSy0LCco',
    appId: '1:312149557905:android:8764a0cc4258fd99e2f530',
    messagingSenderId: '312149557905',
    projectId: 'flutterauth-fe0ce',
    storageBucket: 'flutterauth-fe0ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2QtGXjnutPqzHXRqiU8uur-r9xlNHTsc',
    appId: '1:312149557905:ios:8367d4d6b032a709e2f530',
    messagingSenderId: '312149557905',
    projectId: 'flutterauth-fe0ce',
    storageBucket: 'flutterauth-fe0ce.appspot.com',
    iosClientId: '312149557905-f9nkbqo19tad7355a3ohuhjno7p5b8rl.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2QtGXjnutPqzHXRqiU8uur-r9xlNHTsc',
    appId: '1:312149557905:ios:b3b57ed903a92266e2f530',
    messagingSenderId: '312149557905',
    projectId: 'flutterauth-fe0ce',
    storageBucket: 'flutterauth-fe0ce.appspot.com',
    iosClientId: '312149557905-nhro5su9dr7oog3vo8p60pmcmnlbt6nb.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPage.RunnerTests',
  );
}
